apiVersion: actions.msft.isd.coe.io/v1alpha1
kind: Database
metadata:
  name: database-rbc1
spec:
  # Add fields here
  name: MyDatabase1
  server: 20.97.173.244
  port: 1433
  collation: SQL_Latin1_General_CP1_CS_AS
  sqlManagedInstance: jumpstart-sql
  parameterization: simple # options:[simple, forced]
  allowSnapshotIsolation: true # optional
  allowReadCommittedSnapshot: true
  compatibilityLevel: 150 # optional
  credentials:
    name: credentials
    passwordKey: password
    usernameKey: username
